apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kipj8gssg-python 
  janus-idp.io/tekton: kipj8gssg-python
  backstage.io/kubernetes-id: kipj8gssg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kipj8gssg-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml